### ISSUE TITLE
Misplaced crosshair when opening in modal

### ISSUE THREAD

**Issue by netwarex** [gentics/gentics-ui-image-editor#2]
Hi, this is a really easy to use component, thanks for this. Although, I have some issues.

As mentioned in #1, it would be a good idea to able to set initial values. For now I did it via the modal interface, directly setting the focalPointX and focalPointY, and it works well.

Sadly, sometimes the crosshair is misplaced from the initial set focal point values. eg.: I edit an image, set the coordinates, save it, close the modal. Then I reopen it, it provides the last time saved coordinates, it show up as it should, then after the third or fourth time I reopen the modal this way the crosshair is moved by some pixels left. And after the next reopens it is kept here.

There are some images, where it is not happens. Also when the crosshair misplaced and I click on edit focal point, the editor crosshair is placed on the right place. I think the issue is with the animation of the modal or the size of the image.

Do you have any idea, why does it happens?

Thanks in advance!

**Comment by michaelbromley** [comment]
> As mentioned in #1, it would be a good idea to able to set initial values. 

Not sure what you mean exactly with this, but you can set initial values by binding to the `transform` input.

Regarding the focal point crosshair issue, the fact that it corrects itself after clicking "edit focal point" may suggest that there is some change detection-related issue at play. All the components use the OnPush strategy so perhaps some data update is not being properly reflected in the view. If this is the case, it could be checked by e.g. recreating the error state and then, via the console and `ng.probe()`, manually triggering change detection for the relevant components and seeing if the crosshair jumps to the correct position.
